sudo: required
services:
  - docker

before_install:
  - docker build -t yestay90/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yestay90/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-154956132186"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
